repos:
- hooks:
  - exclude: (^\.bumpversion\.cfg$|cli_messages\.py)
    id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: debug-statements
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
- hooks:
  - additional_dependencies:
    - '@vue/eslint-config-prettier@^4.0.1'
    - babel-eslint@^10.0.1
    - eslint-config-prettier@^3.3.0
    - eslint-plugin-prettier@^3.1.0
    - eslint-plugin-vue@^5.0.0
    - eslint@^5.16.0
    - prettier@^1.15.2
    files: .(js|vue)
    id: eslint
  repo: https://github.com/pre-commit/mirrors-eslint
  rev: v7.14.0
- hooks:
  - entry: poetry run black
    files: .py
    id: black
    language: system
    name: black
    types:
    - python
  - entry: poetry run flake8
    files: .py
    id: flake8
    language: system
    name: flake8
    types:
    - python
  - entry: poetry run isort
    files: .py
    id: isort
    language: system
    name: isort
    types:
    - python
  - args:
    - --py3-plus
    - --py36-plus
    - --keep-mock
    entry: poetry run pyupgrade
    files: .py
    id: pyupgrade
    language: system
    name: pyupgrade
    types:
    - python
  repo: local
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.27.1
