name: 'Dependency Review'

on:
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2

      - name: 'FOSSA Action'
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.MELTYBOT_FOSSA_API_KEY }}
